name: Deploy Production to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: NikitaGlukhi/heroku-pipelines-promoting@v2.1-alpha
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "stage-test-app"
          heroku_email: "glukhi.nikita@gmail.com"
          heroku_promote_to_app: "test-prod-app2"
