name: Deploy Staging to Heroku

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'staging'

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - uses: akhileshns/heroku-deploy@v3.12.13 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "stage-test-app"
          heroku_email: "glukhi.nikita@gmail.com"
