name: Deploy Staging to Heroku

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'staging'
      - uses: akhileshns/heroku-deploy@v3.2.6 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "stage-test-app"
          heroku_email: "glukhi.nikita@gmail.com"
