name: Deploy to prod
on:
  push:
    branches: [ main ]
jobs:
  build_and_deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Deploy to prod
        uses: NikitaGlukhi/firebase-clone-channels@v0
        with:
          firebase_service_account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SELF_EDUCATION_26E10 }}
          project_id: self-education-26e10
          channel_id: staging
          target_project_id: self-education-26e10
          target_channel_id: live
