name: Manually run forkflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Manually run forkflow'
jobs:
  test_job:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        run: echo ${{ ref }}
