name: Deploy to prod (Heroku)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'

      - uses: NikitaGlukhi/heroku-pipelines-promoting@v3.1.0
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "staging-test-app"
          heroku_email: "nikitaglukhi1999@gmail.com"
          heroku_promote_to_app: "production-test-app1"
