name: Deploy Production to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: NikitaGlukhi/heroku-pipelines-promoting@v0
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "stage-test-app"
          heroku_email: "glukhi.nikita@gmail.com"
          heroku_promote_to_app: "test-prod-app1,test-prod-app2"
